---
abstract: 'easily create XMPP packets'
author:
  - 'Martijn van Beers  <martijn@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: XML::Generator::XMPP
name: XML-Generator-XMPP
no_index:
  directory:
    - inc
    - t
provides:
  XML::Generator::XMPP:
    file: lib/XML/Generator/XMPP.pm
    version: 0.02
requires:
  XML::LibXML::XPathContext: 1.63
  XML::SAX::Base: 0
  XML::SAX::IncrementalBuilder::LibXML: 0.02
  perl: 5.6.0
version: 0.02
